CREATE USER WATA IDENTIFIED BY wata;
GRANT CREATE SESSION, CREATE SEQUENCE, CREATE TRIGGER, CREATE TABLE, CREATE PROCEDURE, CREATE VIEW TO WATA;
ALTER USER WATA QUOTA UNLIMITED ON SYSTEM;


-- @C:\Users\Wojtek\Desktop\APLIKACJA_ZAKUPOWA\SYS_CREATE_USER.sql