CREATE USER PRACUJ IDENTIFIED BY pracuj;

GRANT CREATE SESSION, CREATE PROCEDURE, CREATE TABLE, CREATE TRIGGER, CREATE SEQUENCE, CREATE VIEW TO PRACUJ;

ALTER USER PRACUJ QUOTA UNLIMITED ON SYSTEM;

--@C:\Users\Wojtek\Desktop\R_skrypty\APLIKACJE_SHINY\OFERTY\SYS_CREATE_SCHEMA.sql