CREATE OR REPLACE VIEW V_SHOW_CITIES AS
    SELECT NAME AS "MIASTO"
    FROM PRACUJ_CITIES
    ORDER BY NAME;

CREATE OR REPLACE VIEW V_SHOW_TECH AS
	SELECT NAME
	FROM PRACUJ_TECHNOLOGIES
	ORDER BY NAME;


CREATE OR REPLACE VIEW V_PROCESS_CITY_TECH AS
	SELECT 
		CO.ID,
		C.CODE AS "CITY_CODE", 
		T.CODE AS "TECH_CODE",
		C.NAME AS "CITY",
		T.NAME AS "TECH"
	FROM PRACUJ_CITY_OFFER CO
	JOIN PRACUJ_CITIES C ON (C.ID=CO.ID_CITY)
	JOIN PRACUJ_TECHNOLOGIES T ON (T.ID=CO.ID_TECHNOLOGY);
	
CREATE OR REPLACE VIEW V_SHOW_DAY_CITY_OFFER AS
	SELECT 
		C.NAME AS "MIASTO", 
		T.NAME AS "TECHNOLOGIA",
		D.SCRAP_DATE AS "DATA",
		DCO.NUMBER_OF_OFFERS AS "LICZBA"
FROM PRACUJ_DAY_CITY_OFFER DCO
JOIN PRACUJ_CITY_OFFER CO ON (CO.ID=DCO.ID_CITY_OFFER)
JOIN PRACUJ_CITIES C ON (C.ID=CO.ID_CITY)
JOIN PRACUJ_TECHNOLOGIES T ON (T.ID=CO.ID_TECHNOLOGY)
JOIN PRACUJ_DATES D ON (D.ID=DCO.ID_DATE);


--@C:\Users\Wojtek\Desktop\R_skrypty\APLIKACJE_SHINY\OFERTY\VIEWS.sql
